### ISSUE TITLE
can't load layer (sqlite3.OperationalError: cannot commit - no transaction is active)

### ISSUE THREAD

**Issue by riccardoklinger** [heremaps/xyz-qgis-plugin#17]
was trying to load a space with 204 items. had some issues in downloading:
An error has occurred while executing Python code: 

sqlite3.OperationalError: cannot commit - no transaction is active 
Traceback (most recent call last):
  File "/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/XYZHubConnector/plugin.py", line 398, in start_load_layer
    con_load.start_args(args)
  File "/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/XYZHubConnector/modules/loader/layer_loader.py", line 64, in start_args
    self.start( *a, **kw)
  File "/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/XYZHubConnector/modules/loader/layer_loader.py", line 53, in start
    self.layer = XYZLayer(conn_info, meta, tags=tags)
  File "/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/XYZHubConnector/modules/layer/layer.py", line 50, in __init__
    self._init_ext_layer(geom, crs)
  File "/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/XYZHubConnector/modules/layer/layer.py", line 143, in _init_ext_layer
    self._init_constraint(fname, sql_constraint, db_layer_name)
  File "/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/XYZHubConnector/modules/layer/layer.py", line 195, in _init_constraint
    cur.execute(s)
sqlite3.OperationalError: cannot commit - no transaction is active

Python version: 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609] 
QGIS version: 3.4.4-Madeira Madeira, f6ddc62 

Python Path:
/usr/share/qgis/python
/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python
/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/ricckli/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/ricckli/.local/share/QGIS/QGIS3/profiles/default/python
/home/ricckli/.local/lib/python3.5/site-packages/IPython/extensions

**Comment by minff** [comment]
The error is caused by different behavior of sqlite3 in implicit commit in python version prior to 3.6.
The fix is added to [version 1.6.2](/heremaps/xyz-qgis-plugin/releases/tag/1.6.2-alpha).

**Comment by riccardoklinger** [comment]
Thank you for the quick support. But why are you using direct db connections and not simply the API and proper requests.
